name: CI

on:
  push:
    branches:
       - main
       - development
  workflow_dispatch:

jobs:
  my_first_jobs:
    runs-on: macos-latest
    
    steps:
    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: 16
        
    - name: Show version
      run: "node --version"
    
    - name: Get repo
      uses: actions/checkout@v3
      with:
        ref: development
        
    - name: Install dependencies
      run: "npm install"

    - name: Run server in the background
      run: npm start -- --p 5000 --cp 3000 &
        
    - name: Wait for server to start
      run: |
        n=0
        until [ $n -ge 5 ]
        do
          curl -s http://localhost:5000 >/dev/null && break
          n=$[$n+1]
          sleep 5
        done
        
    - name: Stop server
      run: pkill -f "node index.js"
